apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: controllers
  namespace: kafka
  labels:
    strimzi.io/cluster: prod-kafka

spec:
  replicas: 3

  roles:
    - controller

  storage:
    type: persistent-claim
    size: 20Gi
    deleteClaim: false
    kraftMetadata: shared
