apiVersion: apps/v1
kind: Deployment
metadata:
  name: telecom-producer
  namespace: kafka

spec:
  replicas: 3

  selector:
    matchLabels:
      app: telecom-producer

  template:
    metadata:
      labels:
        app: telecom-producer

    spec:
      containers:
      - name: telecom-producer

        image: us-central1-docker.pkg.dev/PROJECT_ID/kafka/telecom-producer:v1

        env:
        - name: BOOTSTRAP_SERVERS
          value: "prod-kafka-kafka-internal-bootstrap:9092"

        resources:
          requests:
            cpu: "1"
            memory: 1Gi

          limits:
            cpu: "2"
            memory: 2Gi
